artists/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.views.generic.base import TemplateView
from artists import views

urlpatterns = patterns('',
    url(r'^artists/$', views.list, name='artist-list'),
    url(r'^artists/my/$', views.apps, name='artist-my'),
    url(r'^artists/(?P<artist_id>\d+)/$', views.apps, name='artist-apps'),
    url(r'^artists/(?P<artist_id>\d+)/apps/$', views.apps, name='artist-apps'),
)

iconmatrix/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from applications import views as app_views

urlpatterns = patterns('',
    url(r'^$', app_views.list, name='index'),
    url(r'', include('accounts.urls')),
    url(r'', include('applications.urls')),
    url(r'', include('artists.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import Form

class SearchForm(Form):

    query = forms.CharField(max_length=200)

templates/base.html
{% load tags %}
{% load static %}
{% load user_filter %}
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}首页{% endblock %} | Icon Matrix</title>
    <link href="{% get_static_prefix %}css/bootstrap.min.css" rel="stylesheet">
    <link href="{% get_static_prefix %}css/bootstrap-theme.min.css" rel="stylesheet">
    <link href="{% get_static_prefix %}css/main.css" rel="stylesheet">
    <link href="{% get_static_prefix %}css/theme-dark.css" rel="stylesheet">
  </head>

    {% url 'index' as index_url %}
    {% url 'auth-logout' as auth_logout_url %}
    {% url 'auth-login' as auth_login_url %}
    {% url 'apps-hot' as apps_hot_url %}
    {% url 'apps-new' as apps_new_url %}

  <body>
      <header class="navbar navbar-inverse navbar-fixed-top" role="banner">
          <div class="container">
              <nav class="collapse navbar-collapse" role="navigation">
                  <div class="navbar-header"><a class="navbar-brand" href="/"><img src="/static/images/logo.png"/></a></div>
                  <ul class="nav navbar-nav">
                      <li class="{% active apps_hot_url %}"><a href="{% url 'apps-hot' %}">最热应用</a></li>
                      <li class="{% active apps_new_url %}"><a href="{% url 'apps-new' %}">最新更新</a></li>
                  </ul>
                  <ul class="nav navbar-nav navbar-right">
                      <form class="navbar-form navbar-left" role="search" action="/apps/search/" method="post">{% csrf_token %}
                              <input id="id_query" maxlength="100" name="query" class="form-control" placeholder="搜索应用">
                      </form>
                      {% if user.is_authenticated %}
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.name }}</a>
                          <ul class="dropdown-menu">
                              <li class="{% active auth_logout_url %}"><a href="{% url 'auth-logout' %}">退出</a></li>
                          </ul>
                      </li>
                      {% else %}
                      <li class="{% active auth_login_url %}"><a href="{% url 'auth-login' %}">微博登录</a></li>
                      {% endif %}
                  </ul>
              </nav>
          </div>
      </header>
      <p style="display:none" id="intro">Icon Matrix 是基于 Smartisan OS 系统的图标的展示网站,纯个人业余制作。所有图标版权归锤子科技及设计师所有。禁止任何转载和盗用。</p>
    {% block container %}
        <h1>Icon Matrix</h1>
    {% endblock %}
    <!--hr-->
    <footer>
    {% block footer %}
    {% endblock %}
    <div class="copyleft"><p><center>本网站是基于 Smartisan OS 系统的重绘图标展示网站，纯个人业余制作。
        图标版权归<a href="http://www.smartisan.com/">锤子科技</a>及设计师所有。禁止任何转载和盗用。<a href="http://weibo.com/smartisanicon/">官方微博</a> | <a href="mailto:iconmatrix@sharpmark.net">反馈邮箱</a></center></p></div>
    </footer>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/main.js"></script>
    <script src="{{ STATIC_URL }}js/jquery.popupoverlay.js"></script>

  </body>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-1267846-21', 'auto');
    ga('send', 'pageview');

  </script>
</html>